Completed javascript-modal exercise
claylevy53/m1-1023-code-solutions pull request #48
Opened 2023-12-23 03:15 UTC by claylevy53

<img width="1350" alt="Screen Shot 2023-12-22 at 7 15 27 PM" src="https://github.com/claylevy53/m1-1023-code-solutions/assets/146284397/1bc70cd7-7a5a-4eaf-9e04-e093f02fcac5">

2024-01-01 18:00 UTC, kurtyazdizadeh requested changes
While this technically works, typically a modal in practice will just show/hide existing HTML elements using javascript to toggle between CSS classes. So you could have a "show" or "hide" class on the modal that you'd toggle between using a click handler on the button to visually show the modal

If you review the README, you'll see all the needed references of HTML/CSS/JS properties to solve the challenge. 

When I assigned this exercise, we didn't do DOM creation yet.

2024-01-02 02:36 UTC, claylevy53 commented
@kurtyazdizadeh Got it, just made the necessary fixes. Let me know if this works

2024-01-02 03:37 UTC, kurtyazdizadeh approved these changes
This technically works, but there is a better way to implement the solution - I'll review it in class!

2024-01-02 03:37 UTC, kurtyazdizadeh commented on javascript-modal/main.js
> +    $modalText.style.display = 'none';
Though this works, there is an easier way to implement this. You could actually write a single callback function that "toggles" the applied CSS classes to the HTML element that triggered the callback.

The CSS classes you toggle will show/hide the element.

2024-01-05 06:15 UTC, merged